# simage is good or bad by using threshold and noise and saturation and edges values

In [ ]:
import cv2
import numpy as np
img = cv2.imread('C:\\Users\\shiri\\OneDrive\\Desktop\\color_ball.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Find the threshold value using Otsu's method
_, threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
# Find the edges
edges = cv2.Canny(img, 100, 200)

# Convert the image to the HSV color space
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv_img)

# Find the maximum and minimum saturation values
min_saturation, max_saturation, _, _ = cv2.minMaxLoc(s)

# Compute the saturation channel of the image
saturation_channel = hsv_img[:,:,1]

#Blur the saturation channel using a Gaussian filter
blurred_saturation_channel = cv2.GaussianBlur(saturation_channel, (5, 5), 0)

# Threshold the saturation channel using Otsu's method
_, thresholded_image = cv2.threshold(blurred_saturation_channel, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)

# Calculate the minimum and maximum pixel values
min_val, max_val, _, _ = cv2.minMaxLoc(gray)

# Calculate the dynamic range
dynamic_range = max_val - min_val

# Compute image intensity
intensity = np.mean(gray)

# Compute image noise
noise = cv2.meanStdDev(gray)[1][0][0]

# Print results
print('Image intensity:', intensity)
print("Darkest intensity:", min_val)
print("Brightest intensity:", max_val)
print("Dynamic range:", dynamic_range)
print('Image noise:', noise)
print("Threshold value:", threshold)
print("Minimum saturation value:", min_saturation)
print(" saturation value:", max_saturation)
print()

if intensity > 100 and noise < 55 and max_saturation > 200:
    print('Image is good')
else:
    print('image is bad')

cv2.imshow('Original Image', img)
cv2.imshow('Gray image',gray)
cv2.imshow('Threshold Image', threshold)
cv2.imshow('Edge Image', edges)
cv2.imshow('Saturation Channel', saturation_channel)
cv2.imshow('noise image', noise)
cv2.imshow('Blurred Saturation Channel', blurred_saturation_channel)
cv2.imshow('Edges', edges)
cv2.imshow('Thresholded Image', thresholded_image)

cv2.waitKey(0)
cv2.destroyAllWindows()


Image intensity: 129.44096020761245
Darkest intensity: 15.0
Brightest intensity: 255.0
Dynamic range: 240.0
Image noise: 54.41396493650266
Threshold value: [[  0   0   0 ... 255 255 255]
 [  0 255 255 ... 255 255 255]
 [  0 255 255 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
Minimum saturation value: 0.0
 saturation value: 255.0

Image is good
